### ISSUE TITLE
Set "Access-Control-Allow-Origin" header to "*"

### ISSUE THREAD

**Issue by neverendingqs** [davemachado/public-api#1]
Request: set the `Access-Control-Allow-Origin` header to `"*"`.

Without setting the [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) to `"*"`, client-side apps are not allowed to load the JSON returned by the service, since `Content-Type` `application/json` is [not considered a simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios).

This makes it hard to build a client-side app against this API.

**Comment by davemachado** [comment]
hi @neverendingqs , thanks for bringing this up. This project went through several iterations before being released, so it looks like this was something that was lost in process. I've made the changes in commit 60f7a6596ad18a811a7a515fe9c3aafe933e2608. Thanks for the interest in the project!
