### ISSUE TITLE
Update digital ocean image in README for dark theme

### ISSUE THREAD

**Issue by divakaranjey** [davemachado/public-api#18]
The powered by digital ocean image in readme is not visible if GitHub dark theme is in use (image attached below). Maybe update to blue badge so that it is seen in both light & dark theme.
<img width="1270" alt="do_badge" src="https://user-images.githubusercontent.com/6598352/122502785-4d75ba00-cfc5-11eb-8992-97009e3055de.png">

**Comment by oxr463** [comment]
Or just use a version that has a white background.

**Comment by davemachado** [comment]
Thanks for calling this out! I've updated the DO logo to use the blue format, which works well for both light and dark theme.
<img width="753" alt="Screen Shot 2021-07-21 at 10 16 29 AM" src="https://user-images.githubusercontent.com/15134885/126505779-a3872542-3478-48b3-a923-1a7a2eb270f3.png">
