### ISSUE TITLE
https://api.publicapis.org/entries is not returning any response on postman

### ISSUE THREAD

**Issue by lexyagi** [davemachado/public-api#23]
I am trying to call this open api https://api.publicapis.org/entries? but it is not returning any response on postman and when accessed via browser it looks like it's empty. Can you kindly assist? Is there anything else I need to set up from my end maybe to call this api?

![image](https://user-images.githubusercontent.com/87930399/126894586-c031d924-3d64-4c5c-b1b5-107649793491.png)

![image](https://user-images.githubusercontent.com/87930399/126894609-401aa924-f0a8-4d65-84db-c86115bf2661.png)

**Comment by davemachado** [comment]
Thanks for reporting! There was a small bug in the configuration file that has now been fixed.
