### ISSUE TITLE
Count key to category endpoint

### ISSUE THREAD

**Issue by matheusfelipeog** [davemachado/public-api#29]
Hi @davemachado ;)

I'm a maintainer of the public-apis project and I was thinking of showing the number of categories at the top of README.md in the same way we show the number of APIs:

![image](https://user-images.githubusercontent.com/50463866/150434335-636b332f-e62f-423c-b9fe-1c8bb71bffc8.png)

But only the category endpoint doesn't have the count key in its return, I think this might be a nice addition.

Example:

```json
{
    "count": 51,
    "categories": [
        "Animals",
        "Anime",
        ...
        "Video",
        "Weather"
    ]
}
```

**Comment by davemachado** [comment]
Hey @matheusfelipeog , thanks for bringing this up!

This definitely sounds like a nice addition. I've added this to my backlog for the week and should get to it over the next few days :)

**Comment by matheusfelipeog** [comment]
> Hey @matheusfelipeog , thanks for bringing this up!
> 
> This definitely sounds like a nice addition. I've added this to my backlog for the week and should get to it over the next few days :)

Perfect 😄

**Comment by davemachado** [comment]
@matheusfelipeog b90cc8e495d327894103f5e7eb7a1b2ad6ac46c3 is now deployed, so you should be good to go!

```
 ~ $ curl https://api.publicapis.org/categories | jq | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   785  100   785    0     0  11056      0 --:--:-- --:--:-- --:--:-- 11056
{
  "count": 51,
  "categories": [
    "Animals",
    "Anime",
    "Anti-Malware",
    "Art & Design",
    "Authentication & Authorization",
    "Blockchain",
    "Books",
    ```

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog [b90cc8e](https://github.com/davemachado/public-api/commit/b90cc8e495d327894103f5e7eb7a1b2ad6ac46c3) is now deployed, so you should be good to go!

Very good, great work @davemachado ❤️ 

A big THANK YOU for implementing this. Now everyone can see the number of categories easily:

![image](https://user-images.githubusercontent.com/50463866/151723186-970ec1ef-e7fe-477a-998c-2eda3ee64be6.png)
