### ISSUE TITLE
[Feature Request]: GET /categories

### ISSUE THREAD

**Issue by EdwinVanRooij** [davemachado/public-api#4]
I'm currently creating an application which first prompts the user to select a category, then asks which subject is of interest. It would be useful to provide a list of categories here.

For now, I'm hard-coding the entries.

**Comment by davemachado** [comment]
Hi @EdwinVanRooij , thanks for the feature request. I've added `GET /categories` as an endpoint with commit 4b2bbc9cae44d920871e6e0c4434f8a87c801be0 -- this will go through the CI/CD pipeline and deploy tonight.
